name: release
on:
  push:
    branches: [master]

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: mauriciolauffer/.github/.github/workflows/release.yml@main
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
