name: Scorecards supply-chain security
on:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    - cron: "10 5 * * 1"
  push:
    branches: [master]

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    permissions:
      security-events: write
      id-token: write
    uses: mauriciolauffer/.github/.github/workflows/scorecards-analysis.yml@main
    secrets:
      SCORECARD_READ_TOKEN: ${{ secrets.SCORECARD_READ_TOKEN }}
