name: test
on:
  push:
  pull_request:
  schedule:
    - cron: "35 1 * * *"


permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: npm i -g @ui5/cli concurrently --ignore-scripts
    - run: npm ci
    - run: npm run build
    - run: npm run lint:ci
    - run: npm run start:test
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: eslint.sarif
