name: test
on:
  push:
    branches: [ master ]
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - run: |
        mkdir target
        npm i @ui5/cli --ignore-scripts
        npm ci --ignore-scripts
        npm run build
        npm run lint:ci
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: target/eslint.sarif
    - run: npm run test:ci
